version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: rambdax
    versions:
    - "> 3.7.0"
  - dependency-name: gatsby-image
    versions:
    - 2.10.0
    - 3.2.0
    - 3.3.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.2.0
  - dependency-name: firebase
    versions:
    - 8.2.4
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
    - 8.3.1
    - 8.3.2
    - 8.3.3
    - 8.4.0
    - 8.4.1
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.23.0
    - 7.24.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 2.15.0
    - 3.2.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.10
    - 2.32.12
    - 2.32.3
    - 2.32.5
    - 2.32.6
    - 2.32.7
    - 2.32.8
  - dependency-name: cssnano
    versions:
    - 4.1.11
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.12.0
    - 3.1.0
    - 3.2.0
  - dependency-name: lazysizes
    versions:
    - 5.3.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 2.9.0
    - 3.1.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 3.1.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 3.1.0
  - dependency-name: gatsby-transformer-yaml
    versions:
    - 2.10.0
    - 3.1.0
  - dependency-name: babel-preset-gatsby
    versions:
    - 1.1.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
    - 4.1.0
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.1
    - 2.13.4
    - 2.14.2
  - dependency-name: "@babel/plugin-proposal-optional-chaining"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.7
    - 7.13.0
  - dependency-name: "@babel/plugin-proposal-nullish-coalescing-operator"
    versions:
    - 7.13.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.0
    - 3.9.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 3.9.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-custom-blocks
    versions:
    - 2.9.0
  - dependency-name: preact
    versions:
    - 10.5.11
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 2.9.0
  - dependency-name: gatsby-plugin-catch-links
    versions:
    - 2.9.0
  - dependency-name: gatsby-remark-images
    versions:
    - 3.10.0
  - dependency-name: gatsby-plugin-google-analytics
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-autolink-headers
    versions:
    - 2.10.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 2.10.0
